#!/bin/bash


#Mostly the same is comparing two files using the =  command
#First read the contents of the  files into variables
#and set both to lower case

if diff -l $1 $2 >/dev/null  ; then

	echo "Mostly the same."
else
	echo "Different."

fi
